name: ci-dmn-ms-workflow
on: push
jobs:
  check-dmn-microservice:
    runs-on: ubuntu-latest                          
    steps:             
      - uses: actions/checkout@v3                   
      - uses: actions/setup-go@v4
        with:                                       
          go-version: '1.20'
          cache-dependency-path: dmn-microservice/go.sum
      - run: ls    
      - name: Install dependencies
        working-directory: ./dmn-microservice
        run: |
          go get .
          go get github.com/confluentinc/confluent-kafka-go/kafka                        
      - name: Build file
        working-directory: ./dmn-microservice
        run: go build .
      - name: Run file
        working-directory: ./dmn-microservice
        run: ./dmn-microservice
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_dmn
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dmn-microservice"
          push: true
          tags: marianalavoura/dmn-microservice:latest
